### ISSUE TITLE
Can you tell me what is the specific configuration of the quantexsr_net_g_best.pth?

### ISSUE THREAD

**Issue by brillianti** [chaofengc/QuanTexSR#4]
Hello, i am using the quantexsr_net_g_best.pth file,so i want to know the config of this file.
What is the specific dataset used for this file? Is it div2k? Did it run 200k times? Is it for scale 4 or scale 2?
I would be very grateful if you could reply to me.

**Comment by chaofengc** [comment]
Please find model config details in the option file ` options/train_QuanTexSR_LQ_stage.yml`, and see the training details in the paper.
The model is trained for 400k iterations, and choose the best validation one. Currently, only `x4` model is provided. Please stay tuned for further updates.

**Comment by brillianti** [comment]
Is this model jointly trained on multiple datasets? I see you are writing 200K in options/train_QuanTexSR_LQ_stage.yml

**Comment by chaofengc** [comment]
Please refer to the implementation details section of the paper.

**Comment by brillianti** [comment]
thanks for your reply
